# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "xenserver-6.5.0-xen"

  # disable mounting of vagrant folder as its not supported on xenserver
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # disable checking for vbguest versions as its not supported on xenserver
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.network :private_network, :auto_config => false , :ip => "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize [ "modifyvm", :id, "--nicpromisc2", "allow-all" ]
  end

end
